default:
	mpicc -o timempi timempi.c -std=gnu99
	mpicc -o timempi2 timempi2.c -std=gnu99

timempi:
	mpicc -o timempi timempi.c -std=gnu99

timempi2:	
	mpicc -o timempi2 timempi2.c -std=gnu99

clean:
	rm timempi
	rm timempi2
